---
title: "Peer-reviewed Publications"
---

If you'd like a pdf of an article and it's not available to you, [email me](mailto:m.koch@ufl.edu).

### In press

+ __Koch, M. K.__, & Wang, Q. (in press) Autobiographical memory. In Levesque (Ed.), _Encyclopedia of Adolescence_. Springer.

+ Garavito, D. M. N., & __Koch, M. K.__ (in press). Coming of age in the eyes of the law: The	conflict between Miranda, J.D.B., and puberty. _American Criminal Law Review_. 

### Recent Publications

+ __Koch, M. K.__, & Mendle, J. (2022). In their own words: Finding meaning in girls’ experiences of	puberty. _Child Development_. https://doi.org/10.1111/cdev.13836

+ __Koch, M. K.__, & Mendle, J. (2021). Real world skills in a virtual world: An innovative activity for teaching developmental psychopathology. _Teaching of Psychology_. https://doi.org/10.1177/00986283211042309

+ __Koch, M. K.__, Mendle, J., & Beam, C. R. (2020) Psychological distress amid change: Role	disruption in girls during the adolescent transition. _Research on Child and Adolescent Psychopathology_, 48, 1211-1222. https://doi.org/10.1007/s10802-020-00667-y

+ Mendle, J., Beam, C. R., McKone, K. M. P., & __Koch, M. K.__ (2020). Puberty and transdiagnostic risks for mental health. Journal of Research on Adolescence, 30, 687	705. https://doi.org/10.1111/jora.12552

+ Mendle, J., & __Koch, M. K.__ (2019). The psychology of puberty: What aren’t we studying that	we should? _Child Development Perspectives_, 13, 166-172.	https://doi.org/10.1111/cdep.12333

+ McGuire, T. G., McCormick, K. C., __Koch, M. K.__, & Mendle, J. (2019). Pubertal maturation	and longitudinal trajectories of depression during early adolescence. _Frontiers in	Psychology_.  https://doi.org/10.3389/fpsyg.2019.01362
