---
title: "Research"
output:
  distill::distill_article:
    toc: true
    css: theme.css
---

```{css echo=FALSE}
d-title h1 {
  color: var(--color-secondary);
}

```

## Overview
I  research how major developmental transitions like puberty affect health outcomes and identity development.
A central aim of my research is to better understand why some individuals navigate transitions that everyone goes through in their lives more adaptively than others.
I use a variety of methods in my research, including surveys, interviewing, diaries, computational text analysis, content coding, and structural equation modeling.

Feel free to [__email me__](mailto:m.koch@ufl.edu) if there is any project listed here that you would like to know more about.


## Peer-Reviewed Publications

**Recent Publications**
+ Garavito, D. M. N., & __Koch, M. K.__ (2023). Coming of age in the eyes of the law: The	conflict between Miranda, J.D.B., and puberty. _American Criminal Law Review_. https://heinonline.org/HOL/LandingPage?handle=hein.journals/amcrimlr60&div=5&id=&page=

+ __Koch, M. K.__, & Wang, Q. (2022) Autobiographical memory. In Levesque (Ed.), _Encyclopedia of Adolescence_. Springer. https://doi.org/10.1007/978-3-319-32132-5_827-1

+ __Koch, M. K.__, & Mendle, J. (2022). In their own words: Finding meaning in girls’ experiences of	puberty. _Child Development_. https://doi.org/10.1111/cdev.13836

+ __Koch, M. K.__, & Mendle, J. (2021). Real world skills in a virtual world: An innovative activity for teaching developmental psychopathology. _Teaching of Psychology_. https://doi.org/10.1177/00986283211042309

+ __Koch, M. K.__, Mendle, J., & Beam, C. R. (2020) Psychological distress amid change: Role	disruption in girls during the adolescent transition. _Research on Child and Adolescent Psychopathology_, 48, 1211-1222. https://doi.org/10.1007/s10802-020-00667-y

+ Mendle, J., Beam, C. R., McKone, K. M. P., & __Koch, M. K.__ (2020). Puberty and transdiagnostic risks for mental health. _Journal of Research on Adolescence_, 30, 687	705. https://doi.org/10.1111/jora.12552

+ Mendle, J., & __Koch, M. K.__ (2019). The psychology of puberty: What aren’t we studying that	we should? _Child Development Perspectives_, 13, 166-172.	https://doi.org/10.1111/cdep.12333

+ McGuire, T. G., McCormick, K. C., __Koch, M. K.__, & Mendle, J. (2019). Pubertal maturation	and longitudinal trajectories of depression during early adolescence. _Frontiers in	Psychology_.  https://doi.org/10.3389/fpsyg.2019.01362

**Under Review**

+ __Koch, M. K.__, Burd, K. & Mendle, J. Same crime, same time? Effects of visual maturity on	juvenile justice decision-making. _(Under Review)_.

+ Porcelli, S., Mendle, J., & __Koch, M. K.__ Mood-based impulsivity and adolescent relationships:	Negative urgency predicts interpersonal problems in youth. _(Under Review)_.

## Conference Presentations

+ __Koch, M. K.__, & Mendle, J. (2022. March). Anger or an Accident? Differences in Explanations	of Adolescents’ Behavior in Ambiguous Legal Scenarios by Sex x Race x Maturation.	Poster presented at the 2022 Biennial Meeting of the Society for Research on	Adolescence. New Orleans, LA.

+ __Koch, M. K.__, & Mendle, J. (2021. April). Text analysis of puberty experiences from	retrospective and concurrent perspectives. Paper presented at the 2021 Biennial Meeting	of the Society for Research in Child Development, Virtual.

+ Porcelli, S., __Koch, M. K.__, & Mendle, J. (2021. April). Untangling rumination and negative	urgency: An exploration of emotional cascade theory in adolescents. Poster presented at	the 2021 Biennial Meeting of the Society for Research in Child Development, Virtual.

+ Kubi, G., __Koch, M. K.__, Ratner, K., & Mendle, J. (2021, March). Perfect fit, or perfectly fixed?:	Identity’s role in anxiety and perfectionism. Poster presented at the Society for Research	on Adolescence. Virtual.

+ Porcelli, S., __Koch, M. K.__, & Mendle, J. (2019, May). Negative urgency and interpersonal	conflict: The mediating role of depressive symptoms. Poster presented at the 31st APS	Annual Convention. Washington, DC.

+ __Koch, M. K.__, Kubi, G., & Mendle, J. (2019, March). Text analysis approaches to predicting	depression in early adolescent girls. Poster presented at the Society for Research on Child	Development. Baltimore, MD.

+ Rosenthal, E., __Koch, M. K.__, & Mendle, J. (2019, March). Is age just a number? Exploring the	association among relative age, pubertal timing, and depression. Poster presented at the	Society for Research on Child Development. Baltimore, MD.

+ __Koch, M. K.__, Royer, C., & Mendle, J. (2019, March). Same time, same crime? Pubertal	maturation and juvenile sentencing. Paper presented at the American Psychology and	Law Society Annual Meeting Portland, OR.

+ __Koch, M. K.__, McKone, K. M. P., & Mendle, J. (2018, April). The pubertal transition and	perceived role disruption. Poster presented at the Society for Research on Adolescence.	Minneapolis, MN.

+ Rosenthal, E., __Koch, M. K.__, Ratner, K., & Mendle, J. (2018, January). ADHD and identity:	Situational influences and individual variability. Poster presented at the Society for Social	Psychology and Personality. Atlanta, GA.

+ Wagner, D., Barry, S., __Koch, M. K.__, Dukhovny, D., Koskela, N., Hood, K., & Harris, M. (2017,	June). Show them the money! Neglecting the economic value of behavioral health for	youth with T1D. Poster presented at the American Diabetes Association Scientific	Sessions. San Diego, CA.

+ __Koch, M. K.__, & Koch, C. (2015, November). Examining the relationship between multi-tasking	and working memory. Poster presented at the Psychonomic Society Meeting. Chicago,	IL.

+ __Koch, M. K.__, & Medina, A. (2015, April). Neuroticism, dysphoria, and autobiographical writing	style. Poster presented at the Western Psychology Conference for Undergraduate	Research. Moraga, CA.

+ Jasper, L., Koch, C. & Koch, M. K. (2013, August). Impact of substance abuse on everyday	memory and attention. Poster presented at the Annual Convention of the American Psychological Association. Honolulu, HI.

+ Koch, C. & __Koch, M. K.__ (2012, November). Shyness, positive and negative affect, life	satisfaction and video games. Poster presented at the Society for Computers in	Psychology. Minneapolis, MN.

+ Jasper, L., Koch, C., & __Koch, M. K.__ (2011, November). The impact of substance abuse on	everyday memory and attention. Poster presented at the Object Perception, Attention, &	Memory Annual Conference. Seattle, WA.
