---
title: "Teaching"
---

```{css echo=FALSE}
d-title h1 {
  color: var(--color-secondary);
}
```

These are some of the classes I have taught as the instructor of record, as well as information about some guest lectures and invited workshops I have done. 
Feel free to contact me if you would like information about any of them.

I have also published course material in _Teaching in Psychology_ on an interactive class summit activity. I developed the activity for a course on Developmental Psychopathology, but the format can be broadly adapted to other courses. These materials are freely available on [OSF](osf.io/47mkh).


## Undergraduate Courses

- Adolescence and Emerging Adulthood (Lecture) at Cornell University
- Unequal Childhoods (Freshmen writing seminar) at Cornell University
- Narratives of Women's Live (Combined lecture/seminar) at Cornell University

## Guest Lectures
- Lecture on depression in Developmental Psychopathology at Cornell University
- Lecture on the psychology of puberty in Adolescence and Emerging Adulthood at Cornell University
- Lecture on end-of-life decision-making in Aging and Adulthood at Cornell University

## Workshops

- Text mining tools for narrative analysis and other mixed-method research (SSEA 2021)
- Topic modeling for psychologists
- Interactional analyses: Empathic Communication
- Content coding: Communion

<br><br><br>